name: Upload Python Package to PYPI

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel build twine

    - name: Get current version from pyproject.toml
      id: get_version
      run: echo "::set-output name=version::$(grep -oP '(?<=version = ")[^"]*' pyproject.toml)"

    - name: Increment version
      id: increment_version
      run: echo "::set-output name=version::$(python -c "version='${{ steps.get_version.outputs.version }}'.split('.'); version[-1] = str(int(version[-1]) + 1); print('.'.join(version))")"

    - name: Update version in pyproject.toml
      run: sed -i "s/version = \".*\"/version = \"${{ steps.increment_version.outputs.version }}\"/" pyproject.toml

    - name: Commit and push changes of pyproject.toml 
      run: |
        git config user.name github-actions and push
        git config user.email github-actions@github.com
        git add pyproject.toml
        git commit -m "Bump version to ${{ steps.increment_version.outputs.version }}"
        git push origin HEAD:${{ github.ref }}


    - name: Build and upload to PyPI
      run: |
        python -m build
        twine upload --password ${{ secrets.PYPI_TOKEN }} dist/*
